# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'base.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CalcDialog(object):
    def setupUi(self, CalcDialog):
        CalcDialog.setObjectName("CalcDialog")
        CalcDialog.resize(439, 570)
        self.buttonBox = QtWidgets.QDialogButtonBox(CalcDialog)
        self.buttonBox.setGeometry(QtCore.QRect(230, 520, 191, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Reset)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(CalcDialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 10, 113, 201))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.qvbl_mode = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.qvbl_mode.setContentsMargins(0, 0, 0, 0)
        self.qvbl_mode.setObjectName("qvbl_mode")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.qvbl_mode.addWidget(self.label)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.qvbl_mode.addWidget(self.line_2)
        self.qrb1_isen = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.qrb1_isen.setChecked(True)
        self.qrb1_isen.setObjectName("qrb1_isen")
        self.qvbl_mode.addWidget(self.qrb1_isen)
        self.qrb2_expa = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.qrb2_expa.setFont(font)
        self.qrb2_expa.setObjectName("qrb2_expa")
        self.qvbl_mode.addWidget(self.qrb2_expa)
        self.qrb3_norm = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.qrb3_norm.setObjectName("qrb3_norm")
        self.qvbl_mode.addWidget(self.qrb3_norm)
        self.qrb4_obli = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.qrb4_obli.setObjectName("qrb4_obli")
        self.qvbl_mode.addWidget(self.qrb4_obli)
        self.qrb5_fann = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.qrb5_fann.setObjectName("qrb5_fann")
        self.qvbl_mode.addWidget(self.qrb5_fann)
        self.qrb6_rayl = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.qrb6_rayl.setObjectName("qrb6_rayl")
        self.qvbl_mode.addWidget(self.qrb6_rayl)
        self.line = QtWidgets.QFrame(CalcDialog)
        self.line.setGeometry(QtCore.QRect(20, 500, 401, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalFrame = QtWidgets.QFrame(CalcDialog)
        self.verticalFrame.setGeometry(QtCore.QRect(20, 380, 401, 121))
        self.verticalFrame.setObjectName("verticalFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.verticalFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.verticalFrame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.verticalFrame)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 1, 0, 1, 2)
        self.qfl_input = QtWidgets.QFormLayout()
        self.qfl_input.setObjectName("qfl_input")
        self.qcb1_input = QtWidgets.QComboBox(self.verticalFrame)
        self.qcb1_input.setObjectName("qcb1_input")
        self.qfl_input.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.qcb1_input)
        self.qdsb1_input = QtWidgets.QDoubleSpinBox(self.verticalFrame)
        self.qdsb1_input.setDecimals(8)
        self.qdsb1_input.setMaximum(999.99)
        self.qdsb1_input.setSingleStep(0.1)
        self.qdsb1_input.setProperty("value", 1.0)
        self.qdsb1_input.setObjectName("qdsb1_input")
        self.qfl_input.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.qdsb1_input)
        self.qdsb2_input = QtWidgets.QDoubleSpinBox(self.verticalFrame)
        self.qdsb2_input.setDecimals(8)
        self.qdsb2_input.setMinimum(-99.0)
        self.qdsb2_input.setProperty("value", 0.0)
        self.qdsb2_input.setObjectName("qdsb2_input")
        self.qfl_input.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.qdsb2_input)
        self.qcb2_input = QtWidgets.QComboBox(self.verticalFrame)
        self.qcb2_input.setObjectName("qcb2_input")
        self.qfl_input.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.qcb2_input)
        self.gridLayout.addLayout(self.qfl_input, 2, 0, 4, 1)
        self.qpb_calculate = QtWidgets.QPushButton(self.verticalFrame)
        self.qpb_calculate.setDefault(True)
        self.qpb_calculate.setObjectName("qpb_calculate")
        self.gridLayout.addWidget(self.qpb_calculate, 2, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.verticalFrame)
        self.checkBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox.setAutoFillBackground(False)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 3, 1, 1, 1)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(CalcDialog)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(140, 10, 281, 361))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setAcceptDrops(False)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.line_4 = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_3.addWidget(self.line_4)
        self.qtw_output = QtWidgets.QTableView(self.verticalLayoutWidget_3)
        self.qtw_output.setAutoFillBackground(False)
        self.qtw_output.setObjectName("qtw_output")
        self.verticalLayout_3.addWidget(self.qtw_output)
        self.horizontalLayoutWidget = QtWidgets.QWidget(CalcDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 340, 111, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.qdsb_gamma = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.qdsb_gamma.setSingleStep(0.1)
        self.qdsb_gamma.setProperty("value", 1.4)
        self.qdsb_gamma.setObjectName("qdsb_gamma")
        self.horizontalLayout.addWidget(self.qdsb_gamma)

        self.retranslateUi(CalcDialog)
        self.buttonBox.accepted.connect(CalcDialog.accept)
        self.buttonBox.rejected.connect(CalcDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(CalcDialog)

    def retranslateUi(self, CalcDialog):
        _translate = QtCore.QCoreApplication.translate
        CalcDialog.setWindowTitle(_translate("CalcDialog", "Caeroc Calculator"))
        CalcDialog.setToolTip(_translate("CalcDialog", "<html><head/><body><p>Input</p></body></html>"))
        self.label.setToolTip(_translate("CalcDialog", "Choos a formula set"))
        self.label.setText(_translate("CalcDialog", " Mode"))
        self.qrb1_isen.setText(_translate("CalcDialog", "Isentropic"))
        self.qrb2_expa.setText(_translate("CalcDialog", "Expansion"))
        self.qrb3_norm.setText(_translate("CalcDialog", "Normal Shock"))
        self.qrb4_obli.setText(_translate("CalcDialog", "Oblique Shock"))
        self.qrb5_fann.setText(_translate("CalcDialog", "Fanno Flow"))
        self.qrb6_rayl.setText(_translate("CalcDialog", "Rayleigh Flow"))
        self.label_3.setText(_translate("CalcDialog", "Input"))
        self.qpb_calculate.setText(_translate("CalcDialog", "Calculate!"))
        self.checkBox.setToolTip(_translate("CalcDialog", "Auto-updates the result as the input is changed"))
        self.checkBox.setText(_translate("CalcDialog", "Auto-Calculate"))
        self.label_4.setToolTip(_translate("CalcDialog", "Tabulated output"))
        self.label_4.setText(_translate("CalcDialog", "Result"))
        self.label_2.setText(_translate("CalcDialog", "ɣ ="))

