# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'base.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CalcDialog(object):
    def setupUi(self, CalcDialog):
        CalcDialog.setObjectName("CalcDialog")
        CalcDialog.resize(522, 541)
        self.buttonBox = QtWidgets.QDialogButtonBox(CalcDialog)
        self.buttonBox.setGeometry(QtCore.QRect(300, 480, 191, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Reset)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(CalcDialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 113, 201))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.qvbl_mode = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.qvbl_mode.setContentsMargins(0, 0, 0, 0)
        self.qvbl_mode.setObjectName("qvbl_mode")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setObjectName("label")
        self.qvbl_mode.addWidget(self.label)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.qvbl_mode.addWidget(self.line_2)
        self.qrb1_isen = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.qrb1_isen.setObjectName("qrb1_isen")
        self.qvbl_mode.addWidget(self.qrb1_isen)
        self.qrb2_expa = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.qrb2_expa.setObjectName("qrb2_expa")
        self.qvbl_mode.addWidget(self.qrb2_expa)
        self.qrb3_norm = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.qrb3_norm.setObjectName("qrb3_norm")
        self.qvbl_mode.addWidget(self.qrb3_norm)
        self.qrb4_obli = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.qrb4_obli.setObjectName("qrb4_obli")
        self.qvbl_mode.addWidget(self.qrb4_obli)
        self.qrb5_fann = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.qrb5_fann.setObjectName("qrb5_fann")
        self.qvbl_mode.addWidget(self.qrb5_fann)
        self.qrb6_rayl = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.qrb6_rayl.setObjectName("qrb6_rayl")
        self.qvbl_mode.addWidget(self.qrb6_rayl)
        self.line = QtWidgets.QFrame(CalcDialog)
        self.line.setGeometry(QtCore.QRect(20, 460, 481, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalFrame = QtWidgets.QFrame(CalcDialog)
        self.verticalFrame.setGeometry(QtCore.QRect(20, 350, 481, 101))
        self.verticalFrame.setObjectName("verticalFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.verticalFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.qpb_calculate = QtWidgets.QPushButton(self.verticalFrame)
        self.qpb_calculate.setObjectName("qpb_calculate")
        self.gridLayout.addWidget(self.qpb_calculate, 2, 1, 1, 1)
        self.qfl_input = QtWidgets.QFormLayout()
        self.qfl_input.setObjectName("qfl_input")
        self.qcb1_input = QtWidgets.QComboBox(self.verticalFrame)
        self.qcb1_input.setObjectName("qcb1_input")
        self.qfl_input.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.qcb1_input)
        self.qdsb1_input = QtWidgets.QDoubleSpinBox(self.verticalFrame)
        self.qdsb1_input.setObjectName("qdsb1_input")
        self.qfl_input.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.qdsb1_input)
        self.qcb2_input = QtWidgets.QComboBox(self.verticalFrame)
        self.qcb2_input.setObjectName("qcb2_input")
        self.qfl_input.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.qcb2_input)
        self.qdsb2_input = QtWidgets.QDoubleSpinBox(self.verticalFrame)
        self.qdsb2_input.setObjectName("qdsb2_input")
        self.qfl_input.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.qdsb2_input)
        self.gridLayout.addLayout(self.qfl_input, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.verticalFrame)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.verticalFrame)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 1, 0, 1, 2)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(CalcDialog)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(140, 10, 361, 321))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.line_4 = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_3.addWidget(self.line_4)
        self.qtw_output = QtWidgets.QTableView(self.verticalLayoutWidget_3)
        self.qtw_output.setObjectName("qtw_output")
        self.verticalLayout_3.addWidget(self.qtw_output)
        self.horizontalLayoutWidget = QtWidgets.QWidget(CalcDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 220, 111, 29))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.qle_gamma = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.qle_gamma.setObjectName("qle_gamma")
        self.horizontalLayout.addWidget(self.qle_gamma)

        self.retranslateUi(CalcDialog)
        self.buttonBox.accepted.connect(CalcDialog.accept)
        self.buttonBox.rejected.connect(CalcDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(CalcDialog)

    def retranslateUi(self, CalcDialog):
        _translate = QtCore.QCoreApplication.translate
        CalcDialog.setWindowTitle(_translate("CalcDialog", "Caeroc Calculator"))
        CalcDialog.setToolTip(_translate("CalcDialog", "<html><head/><body><p>Input</p></body></html>"))
        self.label.setText(_translate("CalcDialog", "1. Mode"))
        self.qrb1_isen.setText(_translate("CalcDialog", "Isentropic"))
        self.qrb2_expa.setText(_translate("CalcDialog", "Expansion"))
        self.qrb3_norm.setText(_translate("CalcDialog", "Normal Shock"))
        self.qrb4_obli.setText(_translate("CalcDialog", "Oblique Shock"))
        self.qrb5_fann.setText(_translate("CalcDialog", "Fanno Flow"))
        self.qrb6_rayl.setText(_translate("CalcDialog", "Rayleigh Flow"))
        self.qpb_calculate.setText(_translate("CalcDialog", "Calculate!"))
        self.label_3.setText(_translate("CalcDialog", "2. Input"))
        self.label_4.setText(_translate("CalcDialog", "3. Result"))
        self.label_2.setText(_translate("CalcDialog", "ɣ ="))
        self.qle_gamma.setText(_translate("CalcDialog", "1.4"))

